### ISSUE TITLE
3D Printable Enclosure

### ISSUE THREAD

**Issue by dalgibbard** [koogar/Gnat-Stats#2]
Hey there,
Just wanted to reach out and say thanks for the great project!
Wasn't sure how best to reach out to you, but I made a compact 3D printable enclosure for use with PhatStats and the TFT + Xiao to turn it into a nice little desk widget; and wanted to give back to you for the cool project :)
For now, I've just popped some files here: https://github.com/dalgibbard/Gnat-Stats/tree/master/other

Feel free to take them and treat them as your own etc (including adding them to your repo as the source of truth if you wish); i've included the STLs ready for printing, but also the fusion360 + STEP files to make it easier to amend them should you need/want to as well.

If it's OK with you, i'll probably pop it onto thingiverse and link your blog/git repo too?

Thanks again!

**Comment by koogar** [comment]
Hi,

Great work and nice enclosure!!! 

Its always nice to hear some feedback and pics, it makes it worth while :)
Feel free to put it on Thingi

PS. Glad you tested it on a XIAO because I have only tested it on a QT-PY.
My XIAO is still in the airbag lol

Regards

Rupert

**Comment by dalgibbard** [comment]
Yeap XIAO worked a treat; it can be a bit fiddly to get it to take the upload from the Arduino IDE, but just needs a press or two on the reset (hence why I added a button for that!).

**Comment by dalgibbard** [comment]
Link is up in case you're interested :)

https://www.thingiverse.com/thing:4812311
