### ISSUE TITLE
Add support for ESP and new display module

### ISSUE THREAD

**Issue by CosmoFox** [koogar/Gnat-Stats#3]
Hello! Tnx for Ur amazing project!
Please add support for esp8266 (like a Wemos D1 or NodeMCU).
And may U add support for 128*128 oled display - ssd1327 (over I2c protocol and SPI)?
I have both devices, and can assist U with this.

**Comment by koogar** [comment]
Hi, 
Sorry I do not have a ssd1327 screen to test.

**Comment by CosmoFox** [comment]
> Hi,
> Sorry I do not have a ssd1327 screen to test.

I have and can help U with tests.
