### ISSUE TITLE
Disable onboard LEDs

### ISSUE THREAD

**Issue by ftb28064212** [koogar/Gnat-Stats#5]
Hello!  I remixed an existing design on Thingiverse to create a custom gnat-stats case for a Pro Micro (https://www.thingiverse.com/thing:4983886), and chose to use clear filament.  This made the device very annoying to use, as the bright red LED would blink every time the software sent data.  To fix this, I just added two lines to the start of the setup code:

pinMode(LED_BUILTIN_TX, INPUT);
pinMode(LED_BUILTIN_RX, INPUT);

Everything still works exactly as expected but no more annoying red light!  It could be worth adding to the code as an option for others, in case anyone else also finds this to be annoying.

**Comment by koogar** [comment]
Thanks for the suggestion :)
